application:
  title: Java Backend Template
  description:
  version: 0.0.0
  termsOfServiceUrl: Terms of service
  license:
  licenseUrl:
  developer:
    name: Kshitij Dhakal
    url:
    email: dhakalkshitij@gmail.com
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/da
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    initialization-mode: always
  #  sql:
  #    init:
  #      mode=always:
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
